### ISSUE TITLE
GetGame called before gameID exists

### ISSUE THREAD

**Issue by nneibaue** [TifMoe/go-fishbowl#37]
When starting a new game (on the home page, after typing in team names), the following error always shows up:

![image](https://user-images.githubusercontent.com/9022917/82597628-80514280-9b66-11ea-8c3e-50a9bf65fa3d.png)

This is being caught here (line 70):
https://github.com/TifMoe/go-fishbowl/blob/2859b562096f027b2985c4d018050f6848952f9a/src/repository/store.go#L67-L72

After doing some digging, I found that in Repository.SaveNewGame, GetGame is called before the gameID is set:

https://github.com/TifMoe/go-fishbowl/blob/2859b562096f027b2985c4d018050f6848952f9a/src/repository/store.go#L35-L65

GetGame is trying to access GameID here:
https://github.com/TifMoe/go-fishbowl/blob/2859b562096f027b2985c4d018050f6848952f9a/src/repository/store.go#L36

but it is not being set util here:
https://github.com/TifMoe/go-fishbowl/blob/2859b562096f027b2985c4d018050f6848952f9a/src/repository/store.go#L59
.

GetGame is called again when the GamePage is loaded here:
https://github.com/TifMoe/go-fishbowl/blob/f9d1865babbc83d1f03dc600a9a800e9cb036b61/ui/src/pages/Game.js#L61-L67

But the error no longer prints to the console because by then the gameID is already set. So we have a situation where GetGame is being called twice in a row with different behavior.

**Comment by TifMoe** [comment]
Hey!! Great call-out! This is definitely not optimal right now (would love any ideas to make it cleaner!) But I think the confusion is coming from the fact that I'm using the repository's GetGame function for two purposes:

1) When creating a new game, I want to see if the random namespace I generated is already on use for another game (bc they'll expire after 2 hrs of inactivity). If a game already exists with that name, I want to return an error to the client. In this case the repository's error is expected 

2) When I'm in an existing game and I need to fetch data, I will run GetGame here too but I'll ensure that I do not get an error back because a repository error is not expected for games already in play

We could make a new repository function whose only job is to see if a game already exists if that's cleaner/clearer :) Let me know if you have any other thoughts!
